import { execSync } from "child_process";
import { writeFileSync } from "fs";
import * as schemas from "./index.ts";

// Settings
const GENERATED_FILE_PATH = "types.ts";

console.log("Compiling schemas...");

// Generate code
let code =
  '// This file is auto generated by /apps/min/packages/schemas/src/tsCompiler.mts\nimport * as schemas from "@min/schemas";import { z } from "zod";\n\n';

for (const schemaName of Object.keys(schemas)) {
  code += `export type ${schemaName.charAt(0).toUpperCase() + schemaName.replace("Schema", "Data").slice(1)} = z.infer<typeof schemas.${schemaName}>;\n`;
}

console.log("Writing to file...");

// Write to file
writeFileSync(GENERATED_FILE_PATH, code);

console.log("Running formatter...");

// Running formatter
execSync(`pnpm exec prettier --write ${GENERATED_FILE_PATH}`);

console.log("Done!");
