// This file is auto generated by /apps/min/packages/schemas/src/tsCompiler.mts
import * as schemas from "@min/schemas";
import { z } from "zod";

export type ChatData = z.infer<typeof schemas.chatSchema>;
export type ChatDataWithParticipants = z.infer<typeof schemas.chatSchemaWithParticipants>;
export type EmojiData = z.infer<typeof schemas.emojiSchema>;
export type MessageData = z.infer<typeof schemas.messageSchema>;
export type MessageDataWithSender = z.infer<typeof schemas.messageSchemaWithSender>;
export type UserData = z.infer<typeof schemas.userSchema>;
