set positional-arguments

@default:
    @just --list

# Clear the build cache
clear:
    flutter clean

# Install dependencies
install:
    flutter pub get

# Run the app
run *args:
    # {{ args }}
    flutter run "$@"

build-linux:
    flutter build linux

build-android:
    flutter build apk --release

install-android: build-android
    adb install -r build/app/outputs/flutter-apk/app-release.apk

build-all:
    flutter build linux
    flutter build apk
