set positional-arguments

@default:
    @just --list

# Install dependencies
install:
    flutter pub get

# Run the app
run *args:
    # {{ args }}
    flutter run "$@"

build-linux:
    flutter build linux

build-android:
    flutter build apk

build-all:
    flutter build linux
    flutter build apk
