name: min_flutter
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
resolution: workspace

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod:
  riverpod_annotation:
  go_router: ^18.0.0
  material_symbols_icons: ^4.2960.0
  min_api:
    path: ../../packages/dart-api
  min_types:
    path: ../../packages/dart-types
  flutter_secure_storage: ^11.0.0
  system_theme: ^3.3.0
  shared_preferences: ^2.5.5
  drift: 2.34.0
  drift_flutter: 0.3.0
  collection: ^1.19.1
  path_provider: ^2.1.6
  cached_network_image_ce: ^4.10.1
  flutter_animate: ^4.5.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: 2.34.0
  riverpod_generator:
  dart_config:
    path: ../../packages/dart-config
  build_runner: ^2.15.1
flutter:
  uses-material-design: true

  fonts:
    - family: GoogleSansFlex
      fonts:
        - asset: assets/fonts/GoogleSansFlex-Variable.ttf
