name: min_flutter
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
resolution: workspace

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod:
  riverpod_annotation:
  go_router: ^17.3.0
  material_symbols_icons: ^4.2960.0
  dart_api:
    path: ../../packages/dart-api
  flutter_secure_storage: ^11.0.0
  system_theme: ^3.3.0
  shared_preferences: ^2.5.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator:
  riverpod_lint:
  custom_lint:
  dart_config:
    path: ../../packages/dart-config
flutter:
  uses-material-design: true

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
